###############################################
############## POCKETS ########################
###############################################

#this locale is only used if there if player's language is not supported
locale: en
debug: false
log.recipes.enable: false

# from org.bukkit.event.inventory.ClickType
open-pocket-action: RIGHT
go-back-to-player-inventory-action-click-type: SHIFT_RIGHT

#this removes players OpenInventory achievement when they join and prevents the achievement from occurring
#so that the server can know each time they open their inventory
rename-items-on-inventory-open: false

default-pocket-color: §5


materials-which-can-have-pockets:
- LEATHER_HELMET
- LEATHER_CHESTPLATE
- LEATHER_LEGGINGS
- LEATHER_BOOTS
- CHAINMAIL_HELMET
- CHAINMAIL_CHESTPLATE
- CHAINMAIL_LEGGINGS
- CHAINMAIL_BOOTS
- IRON_HELMET
- IRON_CHESTPLATE
- IRON_LEGGINGS
- IRON_BOOTS
- DIAMOND_HELMET
- DIAMOND_CHESTPLATE
- DIAMOND_LEGGINGS
- DIAMOND_BOOTS
- DIAMOND_BARDING
- GOLD_HELMET
- GOLD_CHESTPLATE
- GOLD_LEGGINGS
- GOLD_BOOTS
- SADDLE
- CARPET
- PUMPKIN

default-pocket-size-limit: 6
default-allow-pocket-in-pocket: false

require-permissions-general-pocket-use: false
permissions-for-general-pocket-use: pockets.general

require-permissions-pocket-in-pocket-use: false
permissions-for-pocket-in-pocket-use: pockets.pocket-in-pocket

material-settings: 
  LEATHER_HELMET: 
    limit: 1
    allow-pocket-in-pocket: false
  LEATHER_CHESTPLATE: 
    limit: 4
    allow-pocket-in-pocket: false
  LEATHER_LEGGINGS: 
    limit: 8
    allow-pocket-in-pocket: false
  LEATHER_BOOTS: 
    limit: 2
    allow-pocket-in-pocket: false
  CHAINMAIL_HELMET: 
    limit: 1
    allow-pocket-in-pocket: false
  CHAINMAIL_CHESTPLATE:
    limit: 4
    allow-pocket-in-pocket: true
  CHAINMAIL_LEGGINGS:
    limit: 8
    allow-pocket-in-pocket: false
  CHAINMAIL_BOOTS:
    limit: 2
    allow-pocket-in-pocket: false
  IRON_HELMET:
    limit: 1
    allow-pocket-in-pocket: false
  IRON_CHESTPLATE:
    limit: 4
    allow-pocket-in-pocket: false
  IRON_LEGGINGS:
    limit: 8
    allow-pocket-in-pocket: false
  IRON_BOOTS:
    limit: 2
    allow-pocket-in-pocket: false
  DIAMOND_HELMET:
    limit: 2
    allow-pocket-in-pocket: false
  DIAMOND_CHESTPLATE:
    limit: 6
    allow-pocket-in-pocket: false
  DIAMOND_LEGGINGS:
    limit: 10
    allow-pocket-in-pocket: false
  DIAMOND_BOOTS:
    limit: 4
    allow-pocket-in-pocket: false
  DIAMOND_BARDING: 
    limit: 4
    allow-pocket-in-pocket: false
  GOLD_HELMET:
    limit: 2
    allow-pocket-in-pocket: false
  GOLD_CHESTPLATE:
    limit: 5
    allow-pocket-in-pocket: false
  GOLD_LEGGINGS:
    limit: 9
    allow-pocket-in-pocket: false
  GOLD_BOOTS:
    limit: 3
    allow-pocket-in-pocket: false
  SADDLE: 
    limit: 16
    allow-pocket-in-pocket: true
  CARPET: 
    limit: 16
    allow-pocket-in-pocket: true
  PUMPKIN: 
    limit: 12
    allow-pocket-in-pocket: true

recipes-settings.continuous-translation: true

############## RECIPES ############
recipes:
  - pocket


################## BEGIN Pocket ############
recipe.pocket.name: Pocket
recipe.pocket.locales:
  - de
  - ru
  - fr
  - es
recipe.pocket.de.name: Tasche
recipe.pocket.ru.name: Карман
recipe.pocket.fr.name: Poche
recipe.pocket.es.name: Bolsillo

recipe.pocket.rows: 
  - III
  - RRR
  - RRR
recipe.pocket.mats: 
  - R=RABBIT_HIDE
  - I=IRON_INGOT
recipe.pocket.output: FLOWER_POT_ITEM
recipe.pocket.lore: 
  - §ARecipe
  - §5๑P๑
  - §5๑๑๑
  - §5๑_๑
recipe.pocket.de.lore: 
  - §ARezept
  - §5๑T๑
  - §5๑๑๑
  - §5๑_๑
recipe.pocket.ru.lore: 
  - §AРецепт
  - §5๑К๑
  - §5๑๑๑
  - §5๑_๑
recipe.pocket.fr.lore: 
  - §ARecette
  - §5๑P๑
  - §5๑๑๑
  - §5๑_๑
recipe.pocket.es.lore: 
  - Receta
  - §5๑B๑
  - §5๑๑๑
  - §5๑_๑
  
  
messages.pockets-placed-a-pocket-down.en: The item you just placed had a pocket attached. If you pick it back up soon, it might still be there.
messages.pockets-server-restarted-while-pocket-was-open.en: The server has restarted since you opened this pocket. Please re-open it and try again.
messages.pockets-permission-denied.en: Permission denied
messages.pockets-pockets-in-pockets-not-allowed.en: Pockets in pockets not allowed
messages.pockets-object-not-compatible.en: Object not compatible

messages.pockets-placed-a-pocket-down.de: An dem Gegenstand den du gerade platziert hast ist eine Tasche befestigt. Wenn du gleich wieder hin gehst, könntest du deine Sachen noch wieder bekommen.
messages.pockets-server-restarted-while-pocket-was-open.de: Der Server wurde angepasst seit du diese Tasche geöffnet hast. Bitte öffne sie erneut und starte einen weiteren Versuch.
messages.pockets-permission-denied.de: Erlaubnis verweigert!
messages.pockets-pockets-in-pockets-not-allowed.de: Taschen in den Taschen sind nicht erlaubt!
messages.pockets-object-not-compatible.de: Objekt nicht kompatibel
