name: Pockets
version: 1.0.8
main:  com.blocktyper.pockets.PocketsPlugin
author: spaarkimus
website: blocktyper.com
database: false
description: Pockets. Taushen. Bolsillos. Poches. 口袋
commands:
  pockets-test: 
    description: Provides special inventory with testing items. OP only.