name: Pockets
version: 1.1.3
main:  com.blocktyper.pockets.PocketsPlugin
author: spaarkimus
website: blocktyper.com
database: false
description: Pockets. Taushen. Bolsillos. Poches. карманы. 口袋
commands:
  pockets: 
    description: Opens an inventory showing your pockets.
  taschen: 
    description: Öffnet ein Inventar, das Ihre Taschen anzeigt.
  bolsillos: 
    description: Abre un inventario que muestra sus bolsillos.
  poches: 
    description: Ouvre un inventaire qui affiche vos poches.
  карманы: 
    description: Открывает перечень, который отображает ваши карманы.


  pockets-test: 
    description: Provides special inventory with testing items. OP only.